# Relative paths are with respect to YAML file

# Assume the following paths:
# MutectDemo data: TinDaisy/demo/demo_data/MutectDemo-data
#      Params dir: TinDaisy/params
#     current dir: TinDaisy/demo/MutectDemo 
#      Centromere: TinDaisy/params/centromere

tumor_bam:
  class: File
  path: ../demo_data/MutectDemo-data/G15512.HCC1954.1.COST16011_region.bam
normal_bam:
  class: File
  path: ../demo_data/MutectDemo-data/HCC1954.NORMAL.30x.compare.COST16011_region.bam
reference_fasta:
  class: File
  path: ../demo_data/MutectDemo-data/Homo_sapiens_assembly19.COST16011_region.fa

# vcf (vaf length depth) filter config
pindel_vcf_filter_config:
  class: File
  path: ../../params/vcf_filter_config-pindel.ini
strelka_vcf_filter_config:
  class: File
  path: ../../params/vcf_filter_config-strelka.ini
varscan_vcf_filter_config:
  class: File
  path: ../../params/vcf_filter_config-varscan.ini
mutect_vcf_filter_config:
  class: File
  path: ../../params/vcf_filter_config-mutect.ini

# Caller config
pindel_config:
  class: File
  path: ../../params/pindel.WES.ini
strelka_config:
  class: File
  path: ../../params/strelka.WES.ini
varscan_config:
  class: File
  path: ../../params/varscan.WES.ini

# Other filter config
classification_filter_config:
  class: File
  path: ../../params/classification_filter_config.ini
af_filter_config:
  class: File
  path: ../../params/af_filter_config.ini


# Data files
centromere_bed: 
  class: File
  path: ../../params/centromere//ucsc-centromere.GRCh37.bed
dbsnp_db: # this is not correct for MutectDemo, but allows the pipeline to proceed
  class: File
  path: ../demo_data/StrelkaDemo-data/dbsnp-StrelkaDemo.noCOSMIC.vcf.gz

chrlist: # Defining this turns on pindel parallel
  class: File
  path: ../demo_data/MutectDemo-data/chrlist.txt

# Reference and other options
vep_cache_version: "90"
assembly: "GRCh37"
no_delete_temp: true
bypass_vcf2maf: true
