# Relative paths are with respect to YAML file
tumor_bam:
  class: File
  path: ../StrelkaDemo.dat/StrelkaDemoCase.T.bam
centromere_bed:
  class: File
  path: ../StrelkaDemo.dat/ucsc-centromere.GRCh37.bed
dbsnp_db:
  class: File
  path: ../StrelkaDemo.dat/dbsnp-StrelkaDemo.noCOSMIC.vcf.gz
normal_bam:
  class: File
  path: ../StrelkaDemo.dat/StrelkaDemoCase.N.bam
pindel_vcf_filter_config:
  class: File
  path: ../../params/vcf_filter_config-pindel.ini
pindel_config:
  class: File
  path: ../../params/pindel.WES.ini
reference_fasta:
  class: File
  path: ../StrelkaDemo.dat/demo20.fa
strelka_config:
  class: File
  path: ../../params/strelka.WES.ini
strelka_vcf_filter_config:
  class: File
  path: ../../params/vcf_filter_config-strelka.ini
varscan_config:
  class: File
  path: ../../params/varscan.WES.ini
varscan_vcf_filter_config:
  class: File
  path: ../../params/vcf_filter_config-varscan.ini
classification_filter_config:
  class: File
  path: ../../params/classification_filter_config.ini
af_filter_config:
  class: File
  path: ../../params/af_filter_config.ini
vep_cache_version: "90"
assembly: "GRCh37"
no_delete_temp: true
bypass_vcf2maf: true
input_vcf:  # This is used by tindaisy-dbsnp_restart.cwl as input to dbsnp filter step
  class: File
  path: /Users/mwyczalk/Projects/Rabix/TinDaisy/results/tindaisy-2018-10-02-140343.701/root/merge_vcf/results/merged/merged.filtered.vcf
