# test YAML for running C3N-01649 on Cromwell from MGI

# BAM details from /gscuser/mwyczalk/projects/CPTAC3/CPTAC3.catalog/MGI.BamMap.dat
# C3N-01649.WXS.N C3N-01649   CCRC    WXS blood_normal    /gscmnt/gc2741/ding/CPTAC3-data/GDC_import/data/9c91aa54-a11b-4316-a8a9-3aa38aa09771/CPT0088680009.WholeExome.RP-1303.bam   29134914773 BAM hg19    9c91aa54-a11b-4316-a8a9-3aa38aa09771
# C3N-01649.WXS.T C3N-01649   CCRC    WXS tumor   /gscmnt/gc2741/ding/CPTAC3-data/GDC_import/data/e8e6b393-a65b-43c9-982b-7910b5b55eac/CPT0088630009.WholeExome.RP-1303.bam 46195067788    BAM hg19    e8e6b393-a65b-43c9-982b-7910b5b55eac
# TODO: Confirm reference

# Relative paths are with respect to location of this YAML file

tumor_bam:
  class: File
  path: /gscmnt/gc2741/ding/CPTAC3-data/GDC_import/data/9c91aa54-a11b-4316-a8a9-3aa38aa09771/CPT0088680009.WholeExome.RP-1303.bam
normal_bam:
  class: File
  path: /gscmnt/gc2741/ding/CPTAC3-data/GDC_import/data/e8e6b393-a65b-43c9-982b-7910b5b55eac/CPT0088630009.WholeExome.RP-1303.bam
reference_fasta:
  class: File
  path: /gscmnt/gc2521/dinglab/mwyczalk/somatic-wrapper-data/image.data/A_Reference/Homo_sapiens_assembly19.fasta

strelka_config:
  class: File
  path: ../../params/strelka.WES.ini
varscan_config:
  class: File
  path: ../../params/varscan.WES.ini
pindel_config:
  class: File
  path: ../../params/pindel.WES.ini

# VCF Filter args.  These define the VAF, Length, and Depth filter parameters for each caller
pindel_vcf_filter_config:
  class: File
  path: ../../params/vcf_filter_config-pindel.ini
strelka_vcf_filter_config:
  class: File
  path: ../../params/vcf_filter_config-strelka.ini
varscan_vcf_filter_config:
  class: File
  path: ../../params/vcf_filter_config-varscan.ini

# Classification filter config defines which variants retained based on VEP annotation; e.g., exon-only
classification_filter_config:
  class: File
  path: ../../params/classification_filter_config.ini

# Allele frequency filter.  Requires VEP cache
af_filter_config:
  class: File
  path: ../../params/af_filter_config.ini

# Centromere BED used by Pindel caller to exclude difficult regions
centromere_bed:
  class: File
  path: ../../testing/StrelkaDemo.dat/ucsc-centromere.GRCh37.bed

# There are a couple oversions of dbSnP filter.  One is generated using scripts with somaticwrapper:
# Has a hg38 version:
#   Created on denali: /home/mwyczalk_test/src/SomaticWrapper/somaticwrapper/image.setup/B_Filter
#   Stored on denali: /home/mwyczalk_test/data/docker/data/B_Filter
#   Stored on MGI: /gscuser/mwyczalk/projects/SomaticWrapper/data/image.data

# Note that this is somewhat different from Song's version:
#   MGI:/gscmnt/gc3027/dinglab/medseq/cosmic/00-All.brief.pass.cosmic.vcf
#     equivalent, but with .gz and .gz.tbi: /gscmnt/gc2521/dinglab/mwyczalk/somatic-wrapper-data/image.data/B_Filter/00-All.brief.pass.cosmic.vcf.gz
#   denali:/diskmnt/Projects/Users/hsun/data/dbsnp/00-All.brief.pass.cosmic.vcf.gz
dbsnp_db:
  class: File
  path: /gscmnt/gc2521/dinglab/mwyczalk/somatic-wrapper-data/image.data/B_Filter/00-All.brief.pass.cosmic.vcf.gz

# VEP Cache is used for VEP annotation and vcf_2_maf.  
# If not defined, online lookups will be used by VEP annotation. These are slower and do not include allele frequency info (MAX_AF) needed by AF filter.
# For performance reasons, defining vep_cache_gz is suggested for production systems

# Copied from denali:/diskmnt/Projects/Users/mwyczalk/data/docker/data/D_VEP/vep-cache.90_GRCh37.tar.gz
# MGI: /gscmnt/gc2521/dinglab/mwyczalk/somatic-wrapper-data/image.data/D_VEP/vep-cache.90_GRCh37.tar.gz
vep_cache_gz:
  class: File
  path: /gscmnt/gc2521/dinglab/mwyczalk/somatic-wrapper-data/image.data/D_VEP/vep-cache.90_GRCh37.tar.gz
vep_cache_version: "90"
assembly: "GRCh37"

# no_delete_temp = true preserves intermediate files from pindel run and parse
# no_delete_temp: false

input_vcf:  # This is used by tindaisy-dbsnp_restart.cwl as input to dbsnp filter step
  class: File
  path: /gscmnt/gc2741/ding/cptac/cromwell-workdir/cromwell-executions/tindaisy.cwl/ba2d414c-e19e-4fe3-a9c0-fcf4f6595ab8/call-merge_vcf/execution/results/merged/merged.filtered.vcf
