#!/bin/bash

# Matthew Wyczalkowski <m.wyczalkowski@wustl.edu>
# https://dinglab.wustl.edu/

# TODO: check if server is running / available and report reasonable error message
# TODO: RUNLOG is required for queries, but is not known here.

read -r -d '' USAGE <<'EOF'
Cromwell Query: Print out per-case run statistics. Specific to cromwell runs registered with MGI Cromwell database

Usage:
  cq [options] [ RID1 [RID2 ...] ]

Options:
-h: Print this help message
-1: Stop after one
-k CASES_FN: file with list of all cases, one per line, used when RID1 not defined. Default: dat/cases.dat
-q QUERY: type of query, one of 'status', 'logs', 'workflowRoot', 'timing', 'output', 'outputs', 'runlog', 'url'.  Default is `status`
-s STEP: define step of interest for use with 'logs' query
-V: output query result only only (i.e., don't write case and workflow ID)
-U: skip cases were WorkflowID is Unknown or Unassigned
-S: retain only cases where Status is Succeeded
-T: Skip cases where logs are stashed 
-D: Do not access database.  Limited functionality: status is unknown, best guesses are made for other queries.  TODO: complete implementation
-C CROMWELL_URL: define the cromwell URL.  Default: https://genome-cromwell.gsc.wustl.edu
-L RUNLOG: Run log file. Default is "./logs/runlog.dat".  Has to exist unless -f is set.  Can be obtained from environment variable

RID is RunID, and can be either a Case or a WorkflowID.  Examples:
* `cq` - will return status for all cases defined in `dat/cases.dat`
* `cq CASE1 CASE2 CASE3` - returns status of runs for three cases.  TODO: discuss how this looked up
* `cq WID1 WID2` - returns status for two runs with given WorkflowIDs

If RID is - then read RID from STDIN.  If RID is not defined, read from CASES_FN file.

Evaluates the following information for each case
* The workflow ID of the cromwell job
* Various queries from https://genome-cromwell.gsc.wustl.edu/  Supported queries:
    * status - Status of run
    * wid - Workflow ID
    * logs - List of stderr/stdout for each run.  All steps shown unless -s STEP is defined
    * workflowRoot - Path to root of cromwell output
    * timing - URL to visualize timing and progress of workflow
    * output - Output VCF of TinDaisy run associated with tindaisy.cwl.output_vcf
    * outputs - All outputs of TinDaisy run as specified in input CWL
    * runlog - Output status, start, end times
    * url - print URL of Cromwell server and quit.  This is a hardcoded value, but useful to know for manual queries

Workflow ID associated with given cromwell output file is obtaining by grepping for output line like,
[2019-04-14 15:54:01,69] [info] SingleWorkflowRunnerActor: Workflow submitted d6c83416-af3f-46f3-a892-ff1e9074fe74

CROMWELL_URL can be defined as environment variable, e.g., `export CROMWELL_URL=http://localhost:8000`
RUNLOG can be defined as environment variable, e.g., `export RUNLOG=/path/to/logs/runlog.dat`

Note that this script requires `jq` to be installed: https://stedolan.github.io/jq/download/
EOF


source cromwell_utils.sh

# read default from environment variable if possible, otherwise use default
if [ -z $CROMWELL_URL ]; then
    CROMWELL_URL="https://genome-cromwell.gsc.wustl.edu"
fi
CURL_ARG="-k"   # arguments passed to all cromwell db calls 

# read default from environment variable if possible, otherwise use default
if [ -z $RUNLOG ]; then
    RUNLOG="./logs/runlog.dat"
fi

# Defaults
CASES_FN="dat/cases.dat"
QUERY="status"

# http://wiki.bash-hackers.org/howto/getopts_tutorial
while getopts ":h1k:q:s:VUSTDC:L:" opt; do
  case $opt in
    h)
      echo "$USAGE"
      exit 0
      ;;
    1) # Stop after 1
      JUST_ONCE=1
      ;;
    k) 
      CASES_FN="$OPTARG"
      ;;
    q) 
      QUERY="$OPTARG"
      ;;
    s) 
      STEP="$OPTARG"
      ;;
    V) 
      STATUS_ONLY=1
      ;;
    U) 
      NO_UNKNOWN=1
      ;;
    S) 
      ONLY_SUCCESS=1      # What we all hope for
      ;;
    T) 
      NO_STASH=1
      ;;
    D) 
      NO_DB=1
      ;;
    C) 
      CROMWELL_URL="$OPTARG"
      ;;
    L) 
      RUNLOG="$OPTARG"
      ;;
    \?)
      >&2 echo "Invalid option: -$OPTARG"
      echo "$USAGE"
      exit 1
      ;;
    :)
      >&2 echo "Option -$OPTARG requires an argument."
      echo "$USAGE"
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))

# Confirm that `jq` is available
# from https://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script
command -v jq >/dev/null 2>&1 || { echo >&2 "ERROR: jq is not installed.  Quitting"; exit 1; }

# If no DB, status is Unknown
function get_status {
    WID=$1

    if [ $NO_DB ]; then
        echo Unknown
        return
    fi
    URL="$CROMWELL_URL/api/workflows/v1/$WID/status"
    R=$( curl $CURL_ARG -s -X GET $URL -H "accept: application/json" )
    test_exit_status    # This seems like it fails uninformatively if db server not running
    # from /Users/mwyczalk/Projects/Rabix/somatic_sv_workflow/src/make_analysis_summary.sh
    # extract result path from YAML-format result file using `jq` utility, and confirm that it exists
    S=$( echo $R | jq -r '.status' )
    test_exit_status
    echo $S
}

# If no DB, return Unknown (though may be able to guess)
function get_logs {
    WID=$1
    if [ $NO_DB ]; then
        echo Unknown
        return
    fi
    R=$( curl $CURL_ARG -s -X GET "$CROMWELL_URL/api/workflows/v1/$WID/logs" -H "accept: application/json" )
    test_exit_status
    # from /Users/mwyczalk/Projects/Rabix/somatic_sv_workflow/src/make_analysis_summary.sh
    # extract result path from YAML-format result file using `jq` utility, and confirm that it exists
    if [ -z $STEP ]; then
        FILTER=".calls"
    else
        FILTER=".calls.${STEP}[0]"
    fi
    S=$( echo "$R" | jq -r "$FILTER" )
    test_exit_status
    echo "$S"
}

function get_workflowRoot {
    WID=$1
    R=$( curl $CURL_ARG -s -X GET "$CROMWELL_URL/api/workflows/v1/$WID/metadata" -H "accept: application/json" )
    test_exit_status
    S=$( echo "$R" | jq -r '.workflowRoot' )
    test_exit_status
    echo "$S"
}

# This will return one output location, for tindaisy.cwl.output_vcf
function get_output {
    WID=$1
    R=$( curl $CURL_ARG -s -X GET "$CROMWELL_URL/api/workflows/v1/$WID/outputs" -H "accept: application/json" )
    test_exit_status
    S=$( echo "$R" | jq -r '.outputs."tindaisy.cwl.output_vcf".location' )
    test_exit_status
    echo "$S"
}

# This will return ALL outputs specified in CWL.  Note that this will consist of multiple lines
function get_outputs {
    WID=$1
    R=$( curl $CURL_ARG -s -X GET "$CROMWELL_URL/api/workflows/v1/$WID/outputs" -H "accept: application/json" )
    test_exit_status
    # Return all outputs which are not null
    S=$( echo "$R" | jq -r '.outputs[] | .location' )
    test_exit_status
    echo "$S"
}

# runlog returns the fields,
# status, start, end
function get_runlog {
    WID=$1
    STATUS=$(get_status $WID)
    test_exit_status

    START=$( curl $CURL_ARG -s -X GET "$CROMWELL_URL/api/workflows/v1/$WID/metadata" -H "accept: application/json" | jq -r '.start')
    test_exit_status
    END=$( curl $CURL_ARG -s -X GET "$CROMWELL_URL/api/workflows/v1/$WID/metadata" -H "accept: application/json" | jq -r '.end')
    test_exit_status
    printf "$STATUS\t$START\t$END"
}

# this allows us to get Run IDs in one of three ways:
# 1: cq RID1 RID2 ...
# 2: cat cases.dat | cq -
# 3: read from CASES_FN file
# Note that if no Run IDs defined, assume RIDS='-'
if [ "$#" == 0 ]; then
    confirm $CASES_FN
    RIDS=$(cat $CASES_FN)
elif [ "$1" == "-" ] ; then
    RIDS=$(cat - )
else
    RIDS="$@"
fi

# loop over all cases, obtain WID and database status
# If log file does not exist, assume that the run has not started
# RID (run ID) may be either CASE or WorkflowID
for RID in $RIDS; do

    # Skip comments
    [[ $RID = \#* ]] && continue

    # https://stackoverflow.com/questions/2488715/idioms-for-returning-multiple-values-in-shell-scripting
    read CASE WID < <( getCaseWID $RID $RUNLOG )
    test_exit_status

    if [ "$ONLY_SUCCESS" ]; then
        STATUS=$( get_status $WID )
        test_exit_status
        if [ $STATUS != "Succeeded" ]; then
            continue
        fi
    fi

    # Skip runs which are stashed, i.e. those whose logs have been moved to directory logs/WorkflowID
    if [ $NO_STASH ]; then
        ISS=$(isStashed $RID)
        test_exit_status
        if [ $ISS == 1 ]; then
            continue
        fi
    fi

    # Get status for various queries, but avoid db queries to server if WID unknown / unassigned
    if [[ $WID == "Unknown" ]] || [[ $WID == "Unassigned" ]]; then
        if [ "$NO_UNKNOWN" ]; then
            continue
        fi
        STATUS="Unknown"
    else
        if [ "$QUERY" == 'logs' ]; then
            STATUS=$(get_logs $WID)
            test_exit_status
            STATUS=$(printf "\n$STATUS")
        elif [ "$QUERY" == 'status' ]; then
            STATUS=$(get_status $WID)
            test_exit_status
        elif [ "$QUERY" == 'wid' ]; then
            STATUS=$WID
        elif [ "$QUERY" == 'workflowRoot' ]; then
            STATUS=$(get_workflowRoot $WID)
            test_exit_status
        elif [ "$QUERY" == 'timing' ]; then
            # URL as provided by tmooney on slack 
            STATUS="$CROMWELL_URL/api/workflows/v1/$WID/timing"
        elif [ "$QUERY" == 'output' ]; then     # this returns output associated with tindaisy.cwl.output_vcf
            STATUS=$(get_output $WID)
            test_exit_status
        elif [ "$QUERY" == 'outputs' ]; then    # this returns multiple outputs
            STATUS=$(get_outputs $WID | grep -v -w "null")
            test_exit_status
        elif [ "$QUERY" == 'runlog' ]; then
            STATUS=$(get_runlog $WID)
            test_exit_status
        elif [ "$QUERY" == 'url' ]; then
            echo $CROMWELL_URL
            exit 0
        else 
            >&2 echo ERROR: Unknown query $QUERY
            >&2 echo "$USAGE"
            exit 1
        fi
    fi

    # Note that STATUS can have one or multiple lines (in the case of outputs query).  Awk deals with this correctly
    if [ -z $STATUS_ONLY ]; then
        echo "$STATUS" | awk -v c=$CASE -v w=$WID '{OFS="\t"}{print c,w,$0}'
    else
        printf "$STATUS\n" 
    fi

    if [ $JUST_ONCE ]; then
        >&2 echo Stopping after one
        break
    fi

done 




